#!/usr/bin/env groovy
pipeline {
    agent {
        docker { image 'app:latest' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'app --version'
                sh 'svn --version'
            }
        }
    }
}