#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('App') {
            steps {
                sh 'app --version'
                sh 'svn --version'
            }
        }
    }
}