#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Build Docker Image'){
            sh 'docker build -t app:latest '

        }
        stage('App') {
            steps {
                sh 'docker run -d -p 5000:5000 app:latest'
                
            }
        }
    }
}